name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Secret Reading
      run: |
        echo "Testing if secrets can be read..."
        echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"
        echo "ORG_ID length: ${#ORG_ID}"
        echo "PROJECT_ID length: ${#PROJECT_ID}"
        
        if [ -z "$VERCEL_TOKEN" ]; then
          echo "❌ VERCEL_TOKEN is empty"
          exit 1
        else
          echo "✅ VERCEL_TOKEN is set (length: ${#VERCEL_TOKEN})"
        fi
        
        if [ -z "$ORG_ID" ]; then
          echo "❌ ORG_ID is empty"
          exit 1
        else
          echo "✅ ORG_ID is set: $ORG_ID"
        fi
        
        if [ -z "$PROJECT_ID" ]; then
          echo "❌ PROJECT_ID is empty"
          exit 1
        else
          echo "✅ PROJECT_ID is set: $PROJECT_ID"
        fi
        
        echo "🎉 All secrets are readable!"
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        ORG_ID: ${{ secrets.ORG_ID }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
